### ISSUE TITLE
Use of bellini?

### ISSUE THREAD

**Issue by jkgit** [atisharma/bellini#1]
This isn't really a bug I don't think, but is it possible to use Bellini on a Linux desktop like Ubuntu?  Or is it "hardwired" to the display on a Raspberry Pi?  I got it compiled on Ubuntu, hooked up some fonts, and ran 'bellini', and nothing happens.  Well, something does happen, it shows a cursor.  According to strace it is constantly scanning for changes in the config file.  

Edit : I should mention I'm using Alsa input and have the same input working fine in Cava.

Edit 2 : Never mind, figured out how to see it.  Learn something new every day in Linux!

**Comment by atisharma** [comment]
I know you solved the issue, but for future searchers, it writes directly to the framebuffer. So if you switch to tty1 you will see the output.
I'll close the issue and if you have further related question you can re-open.

**Comment by atisharma** [comment]
If you are still interested, bellini now outputs to SDL, so will open up a window in your window manager like any other application.
