### ISSUE TITLE
Question: How to get the input buffer correcty?

### ISSUE THREAD

**Issue by chincheta0815** [atisharma/bellini#3]
I do not know how to contact you in any other way so please mind the question here:
I am trying to combine cava/bellini with squeezelite in a way to steer a hue light system via sound for the Logitech Media Server.
Therefore I use a program by philippe44 which checks for the player "the hue system" and then start analyzing the music stream...

Right now I have some issues that the music is not in sync with my "light output" and I get segfault during its run.

Therefore, I mainly copied & adapted the respective lines of code in cava.

My question now to you:
Is there a possibility that you might have a look onto my "buffer import" into the sound analysis part? I fear that I simply do something wrong there.

Any help, even with some explanation on how that might be done (overlapping of the old buffer with the new one; my biggest problem) is welcome.

Thank you very much in advance for any kind of answer.

The sound stream is to be processed here: https://github.com/chincheta0815/LMS-to-Hue/blob/5ba86894666fed31a4032e594eddf3c12f979a1c/helper/LMS-to-Hue/squeezetiny/output_huebridge.c#L87
and the responsible function is here: https://github.com/chincheta0815/LMS-to-Hue/blob/5ba86894666fed31a4032e594eddf3c12f979a1c/helper/LMS-to-Hue/huebridge/hue_analyze.c#L150

**Comment by atisharma** [comment]
I have absolutely no idea, sorry. I did hack away at the shmem in cava, but only had the minimal required understanding of the memory model. Also there may be differences between OS X and linux (max shmem file size, etc?)
