### ISSUE TITLE
Question concerning Equation (Reference or so)

### ISSUE THREAD

**Issue by chincheta0815** [atisharma/bellini#4]
Sorry to bother you again:
I am trying to understand the ppm part of your code.

Could you help me to explain this line:
https://github.com/atisharma/bellini/blob/d911b0bbf9d995c639758e95ccdbfbf49a1ee9b4/bellini.c#L488

I do not get the part with the exp(): Where does that come from?
and
Why os there a dt involved? I thought ppm is an average of the samples having a amplitude unit without time (e.g. V and not V/s)....

A reference where I can read that on my own would help I think, but I do not know where to look...

My target overall goal is changing the decay time to a lower value and I do not see how...

**Comment by atisharma** [comment]
The exp(...) is the exponential decay from the single pole.
The calculations are my own from the specification referenced in the code.
The PPM average is a decaying average over time, so is described by a
stable single pole system forced by the current V. The dt arises as it
is integrated in time.

If you just want to change the decay time you can change the numerical
constant -1.3545.
